#!/usr/bin/env bash

#
# npm-diff(1)
#
# MIT licensed
# (c) 2014 Segment.io <friends@segment.io>
# (c) 2018 Julian Gruber <mail@juliangruber.com>
#

set -e

color=false
while getopts ":c" opt
do
  case $opt in
    c|color)
    color=true
    shift
    ;;
  esac
done

# arguments

if [[ $# != 3 ]]; then
  echo "Usage: npm-diff [-c] <module> <versionA> <versionB>"
  echo "Example: npm-diff intersect 0.0.0 0.1.0"
  echo "Example with color output (needs colordiff): npm-diff -c intersect 0.0.0 0.1.0"
  exit 1
fi

if ! [ -x "$(command -v colordiff)" ] && [ "$color" = true ]; then
    echo "'colordiff' is not installed. Execute the command without color flag or install colordiff"
    exit
fi

module=$1
a=$2
b=$3
aurl=$(npm show $module@$a dist.tarball 2>/dev/null)
burl=$(npm show $module@$b dist.tarball 2>/dev/null)

# work dir

work=/tmp/$RANDOM
mkdir $work
cd $work

# download

download(){
  version=$1
  url=$2
  mkdir $version
  cd $version

  user=""
  if [ "$(npm config get always-auth)" == "true" ]; then
    user="--user $(cat ~/.npmrc | grep _auth | cut -d' ' -f3 | base64 --decode)"
  fi

  curl --fail --silent --insecure $user $url | tar -xz --strip 1
  if [[ ${PIPESTATUS[0]} != 0 ]]; then
    echo "Unknown version: $module@$1"
    exit 1
  fi
}

download $a $aurl &
download $b $burl &

for job in `jobs -p`; do wait $job || exit 1; done

# diff

diffCommand='diff 
  --recursive 
  --unified 
  --exclude test 
  --exclude Makefile 
  $a $b 
  | egrep -v "\"readme\"|\"_id\"|\"_from\"|\"_resolved\""'

if [ "$color" = true ] ; then
    diffCommand+="| colordiff"
fi

eval $diffCommand

# cleanup

rm -Rf $work

